spring.application.name=api
# Configuración del servidor
server.port=8080
# Forzar codificación UTF-8 en las respuestas HTTP
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Forzar codificación UTF-8 al ejecutar scripts de inicialización SQL
spring.sql.init.encoding=UTF-8

# Añadir el parámetro de charset a la conexión de H2
spring.datasource.url=jdbc:h2:mem:catalogdb;CHARACTER_SET=UTF-8

# Configuración de H2 Database
spring.datasource.url=jdbc:h2:mem:catalogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Mostrar las consultas SQL en consola (útil para depurar)
spring.jpa.show-sql=true

